baseURL = 'https://aditya-c2512.github.io/'
locale = 'en-US'
title = 'Aditya Choubey'

enableRobotsTXT = true
pygmentsStyle = "monokai"

[params]
  footer = "Aditya Choubey"
  description = "MSc Computer Science student at the University of Edinburgh."
  avatarURL = "/images/main.jpg"
  AvatarAltText = "avatar"
  accentColor = "#2563EB"
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/aditya-choubey-20bb9a1b3"},
    {name = "email", url = "mailto:adityachoubey2512@gmail.com"},
    {name = "github", url = "https://github.com/aditya-c2512"},
    {name = "substack", url = "https://adityac2512.substack.com/"}
  ]
  metaKeywords = ["aditya-c2512", "aditya", "choubey", "vulkan", "graphics"]

[menu]
  [[menu.main]]
    identifier = "experience"
    url = "/experience/"
    name = "Experience"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    url = "/projects/"
    name = "Projects"
    weight = 2

  [[menu.main]]
    identifier = "showcase"
    name = "Showcase"
    url = "/showcase/"
    weight = 3

  [[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    url = "/blogs/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    url = "/#contact"
    name = "Get in touch"
    weight = 5