baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Aditya Choubey'

theme = "gokarna"

enableRobotsTXT = true
pygmentsStyle = "monokai"

[params]
  footer = "Aditya Choubey"
  description = "Graphics and Game Programmer."
  avatarURL = "/images/main.jpg"
  AvatarAltText = "avatar"
  accentColor = "#CAD685"
  avatarSize = "size-m"
  #showPostsOnHomePage = "popular"
  ShowBackToTopButton = true # true or false for "back to top" button on posts
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="icon" href="/images/profile_pic.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  socialIcons = [
    {name = "twitter", url = "https://twitter.com/aditya_c2512"},
    {name = "linkedin", url = "https://www.linkedin.com/in/aditya-choubey-20bb9a1b3"},
    {name = "email", url = "mailto:adityachoubey2512@gmail.com"},
    {name = "github", url = "https://github.com/aditya-c2512"}
  ]
  metaKeywords = ["aditya-c2512", "aditya", "choubey", "vulkan", "graphics"]

[menu]
    [[menu.main]]
        identifier = "projects"
        url = "/projects/"
        name = "Projects"
        pre = "<span data-feather='code'></span>"
        weight = 1

    [[menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase/"
        pre = "<span data-feather='eye'></span>"
        weight = 2

    [[menu.main]]
        identifier = "blogs"
        name = "Blogs"
        url = "/blogs/"
        pre = "<span data-feather='book'></span>"
        weight = 3
    
    [[menu.main]]
        identifier = "github"
        url = "https://github.com/aditya-c2512"
        weight = 4
        pre = "<span data-feather='github'></span>"